gb/gshop/gshop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

gb/gshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='index'),
    path('create/', ordersapp.OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', ordersapp.OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='delete'),
    #path('product/<int:pk>/price/', ordersapp.get_product_price),
]

gb/gshop/ordersapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.functional import cached_property
from mainapp.models import Product


class Order(models.Model):
    STATUS_FORMING = 'F'
    STATUS_SENDED = 'S'
    STATUS_PAID = 'P'
    STATUS_DELAYED = 'D'

    STATUS_CHOICES = (
        (STATUS_FORMING, 'формируется'),
        (STATUS_SENDED, 'отправлен'),
        (STATUS_PAID, 'оплачен'),
        (STATUS_DELAYED, 'отменен'),
    )

    user = models.ForeignKey(get_user_model(),
                             on_delete=models.CASCADE,
                             related_name='orders')
    add_datetime = models.DateTimeField('время', auto_now_add=True)
    update_datetime = models.DateTimeField('время', auto_now=True)
    status = models.CharField('статус', max_length=1,
                              choices=STATUS_CHOICES,
                              default=STATUS_FORMING)
    is_active = models.BooleanField(verbose_name='активен',
                                    default=True)

    @cached_property
    def is_forming(self):
        return self.status == self.STATUS_FORMING

    @property
    def total_quantity(self):
        return sum(map(lambda x: x.quantity, self.items.all()))

    @property
    def total_cost(self):
        return sum(map(lambda x: x.product_cost, self.items.all()))

    @property
    def summary(self):
        items = self.items.all()
        return {
            'total_quantity': sum(map(lambda x: x.quantity, items)),
            'total_cost': sum(map(lambda x: x.product_cost, items)),
        }

    def delete(self, using=None, keep_parents=False):
        for item in self.items.all():
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()

    class Meta:
        ordering = ('-add_datetime',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'


class OrderItemManager(models.QuerySet):
    def delete(self):
        print('OrderItem QS delete')


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              on_delete=models.CASCADE,
                              related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('количество', default=0)
    add_datetime = models.DateTimeField('время', auto_now_add=True)
    update_datetime = models.DateTimeField('время', auto_now=True)

    # @property
    # def product_cost(self):
    #     return self.product.price * self.quantity

    @cached_property
    def product_cost(self):
        return self.product.price * self.quantity

    @classmethod
    def get_item(cls, pk):
        # return cls.objects.filter(pk=pk).first()
        return cls.objects.select_related('product').filter(pk=pk).first()

gb/gshop/ordersapp/forms.py
from django import forms
from django.forms import HiddenInput
from mainapp.models import Product

from ordersapp.models import Order, OrderItem


class BaseOrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'user':
                field.widget = HiddenInput()
            field.widget.attrs['class'] = 'form-control'


class OrderForm(BaseOrderForm):
    class Meta:
        model = Order
        fields = ('user',)


class OrderItemForm(BaseOrderForm):
    price = forms.FloatField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        products = Product.get_items()
        self.fields['product'].queryset = products

    def clean_qty(self):
        quantity = self.cleaned_data.get('quantity')
        product = self.cleaned_data.get('product')
        if quantity > product.quantity:
            raise forms.ValidationError('недостаточно на складе!')
        return quantity

    class Meta:
        model = OrderItem
        fields = '__all__'

gb/gshop/ordersapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from ordersapp.forms import OrderForm, OrderItemForm
from ordersapp.models import Order, OrderItem


class LoggedUserOnlyMixin:
    @method_decorator(user_passes_test(lambda user: user.is_authenticated))
    def dispatch(self, request, *args, **kwargs):
        return super().dispath(request, *args, **kwargs)


class OrderList(LoggedUserOnlyMixin, ListView):
    model = Order

    def get_queryset(self):
        return self.request.user.orders.all()


class OrderCreate(LoggedUserOnlyMixin, CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(Order, OrderItem,
                                             form=OrderItemForm, extra=3)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, self.request.FILES)
        else:
            context['form'].initial['user'] = self.request.user
            basket_items = self.request.user.basket.all()
            if basket_items and basket_items.count():
                OrderFormSet = inlineformset_factory(
                    Order, OrderItem, form=OrderItemForm,
                    extra=basket_items.count() + 1
                )
                formset = OrderFormSet()
                for form, basket_item in zip(formset.forms, basket_items):
                    form.initial['product'] = basket_item.product
                    form.initial['quantity'] = basket_item.quantity
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            order = super().form_valid(form)
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
                self.request.user.basket.all().delete()
        if self.object.total_cost == 0:
            self.object.delete()

        return order


class OrderUpdate(LoggedUserOnlyMixin, UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(
            Order, OrderItem, form=OrderItemForm, extra=1
        )
        if self.request.POST:
            formset = OrderFormSet(
                self.request.POST,
                self.request.FILES,
                instance=self.object
            )
        else:
            queryset = self.object.items.select_related('product')
            # formset = OrderFormSet(instance=self.object)
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                instance = form.instance
                if instance.pk:
                    form.initial['price'] = instance.product.price
        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            order = super().form_valid(form)
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
                self.request.user.basket.all().delete()

        if self.object.total_cost == 0:
            self.object.delete()

        return order


class OrderDetail(LoggedUserOnlyMixin, DetailView):
    model = Order


class OrderDelete(LoggedUserOnlyMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('orders:index')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.STATUS_PAID
    order.save()

    return HttpResponseRedirect(reverse('orders:index'))


@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    print('orderitem save')
    if instance.pk:
        instance.product.quantity += sender.get_item(instance.pk).quantity - \
                                     instance.quantity

    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    print('orderitem delete')
    instance.product.quantity += instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=Order)
def product_quantity_update_delete(sender, instance, **kwargs):
    print('orderdelete')


def get_product_price(request, pk):
    pass

gb/gshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="order_container">
    {% block container %}

    {% endblock %}
</div>
</body>
</html>

gb/gshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block container %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc__order_summary.html' %}
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>

        <a href="{% url 'orders:index' %}" class="btn btn-success">отмена</a>
    </div>
{% endblock %}

gb/gshop/ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block container %}
{% include 'ordersapp/includes/inc__order_summary.html' %}
<div class="basket_list">
    {% for item in object.items.all %}
    <div class="basket_record">
        <img src="{{ item.product.image|media_folder_products }}"
             alt="{{ item.product.short_desc }}">
        <span class="category_name">{{ item.product.category.name }}</span>
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbspруб</span>
        <span class="product_quantitiy">x {{ item.quantity }} шт.</span>
        <span class="product_cost"> = {{ item.product_cost }}&nbspруб</span>
    </div>
    {% endfor %}
</div>
{% include 'ordersapp/includes/inc__order_actions.html' %}

{% endblock %}

gb/gshop/ordersapp/templates/ordersapp/order_form.html
a{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block container %}
{% include 'ordersapp/includes/inc__order_summary.html' %}
<div class="order_form">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for item_form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in item_form.visible_fields %}
                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                    {{ field.label|capfirst }}
                </th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in item_form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                    {% if forloop.first %}
                    {% for hidden in item_form.hidden_fields %}
                    {{ hidden }}a
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name == 'price' %}
                    <span class="items-{{ forloop.parentloop.counter0 }}-price">
                                        {{ field.value|default:"0,00" }}
                                    </span> руб
                    {% else %}
                    {% if field.name == 'product' %}
                    {% cache 3600 itemform_product field.value %}
                    {{ field }}
                    {% endcache %}
                    {% else %}
                    {{ field }}
                    {% endif %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <input type="submit" value="сохранить"
               class="btn btn-default btn-round form-control last">
        {% include 'ordersapp/includes/inc__order_actions.html' %}
    </form>
</div>
{% endblock %}

gb/gshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block container %}
{% if not object_list %}
<div class="h2 text-center head">
    Заказов пока нет
</div>
{% else %}
<div class="h2 text-center head">
    Ваши заказы, {{ user.first_name|default:'пользователь'|title }}
</div>
<table class="table orders_list">
    <thead>
    <tr>
        <th>ID</th>
        <th>Создан</th>
        <th>Обновлен</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object_list %}
    <tr>
        <td class="td1 orders_list">{{ item.pk }}</td>
        <td>{{ item.add_dt|date:"Y-m-d H:i:s" }}</td>
        <td>{{ item.update_dt|date:"Y-m-d H:i:s" }}</td>
        <td>{{ item.get_status_display }}</td>
        <td>
            <a href="{% url 'orders:read' item.pk %}">
                посмотреть
            </a>
        </td>
        <td>
            {% if item.is_forming %}
            <a href="{% url 'orders:update' pk=item.pk %}">
                редактировать
            </a>
            {% endif %}
        </td>
        <td>
            {% if item.is_forming %}
            <a href="{% url 'orders:delete' item.pk %}">
                удалить
            </a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}

<a href="{% url 'main:index' %}"
   class="btn btn-default btn-round">
    на главную
</a>

<a href="{% url 'orders:create' %}"
   class="btn btn-default btn-round">
    новый
</a>

{% endblock %}