gb/gshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.index, name='index'),
    path('user/update/<int:user_pk>/', adminapp.ShopUserAdminUpdate.as_view(),
         name='user_update'),
    path('user/delete/<int:user_pk>/', adminapp.user_delete, name='user_delete'),
    path('categories/', adminapp.ProductCategoryList.as_view(), name='categories'),
    path('category/create/', adminapp.ProductCategoryCreate.as_view(),
         name='category_create'),
    path('category/update/<int:pk>/', adminapp.ProductCategoryUpdate.as_view(),
         name='category_update'),
    path('category/delete/<int:pk>/', adminapp.ProductCategoryDelete.as_view(),
         name='category_delete'),
    path('category/<int:pk>/products/', adminapp.category_products, name='category_products'),
    path('category/<int:category_pk>/product/create/', adminapp.category_product_create,
         name='category_product_create'),
    path('product/<int:pk>/', adminapp.ProductDetail.as_view(), name='product_view'),
]

gb/gshop/gshop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

gb/gshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', mainapp.products, name='products'),

    path('category/<int:pk>/', mainapp.category, name='category'),
    path('product/<int:pk>/price/', mainapp.get_product_price),
    path('product/<int:pk>/', mainapp.product_page, name='product_page'),

]

gb/gshop/adminapp/models.py
from django.db import models

# Create your models here.

gb/gshop/mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продуктов'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}({self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.select_related('category'). \
            filter(is_active=True, category__is_active=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']

gb/gshop/adminapp/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelForm, HiddenInput

from authapp.forms import ShopUserChangeForm
from mainapp.models import ProductCategory, Product


class AdminShopUserUpdateForm(ShopUserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password',
                  'email', 'age', 'avatar',
                  'is_staff', 'is_superuser', 'is_active')


class AdminProductCategoryCreateForm(ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class AdminProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'category':
                field.widget = HiddenInput()

gb/gshop/adminapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView

from adminapp.forms import AdminShopUserUpdateForm, AdminProductCategoryCreateForm, AdminProductUpdateForm
from mainapp.models import ProductCategory, Product


class SuperUserOnlyMixin:
    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PageTitleMixin:
    page_title_key = 'page_title'
    page_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.page_title_key] = self.page_title
        return context


@user_passes_test(lambda user: user.is_superuser)
def index(request):
    all_users = get_user_model().objects.all()
    # forms = []
    # for user in all_users:
    #     forms.append(form(user))
    context = {
        'page_title': 'админка/пользователи',
        'all_users': all_users,
    }
    return render(request, 'adminapp/index.html', context)


class ShopUserAdminUpdate(SuperUserOnlyMixin, UpdateView):
    model = get_user_model()
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('new_admin:index')
    pk_url_kwarg = 'user_pk'


@user_passes_test(lambda user: user.is_superuser)
def user_delete(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if not user.is_active or request.method == 'POST':
        if user.is_active:
            user.is_active = False
            user.save()
        return HttpResponseRedirect(reverse('new_admin:index'))
    context = {
        'page_title': 'админка/пользователи/удаление',
        'user_to_delete': user
    }
    return render(request, 'adminapp/user_delete.html', context=context)


class ProductCategoryList(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ProductCategory
    page_title = 'админка/категории'


class ProductCategoryCreate(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ProductCategory
    form_class = AdminProductCategoryCreateForm
    success_url = reverse_lazy('new_admin:categories')
    page_title = 'админка/категории/создание'


class ProductCategoryUpdate(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ProductCategory
    form_class = AdminProductCategoryCreateForm
    success_url = reverse_lazy('new_admin:categories')
    page_title = 'админка/категории/редактирование'


class ProductCategoryDelete(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('new_admin:categories')
    page_title = 'админка/категории/удаление'


@user_passes_test(lambda u: u.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    object_list = category.product_set.all()
    context = {
        'page_title': f'категория {category.name}/продукты',
        'category': category,
        'object_list': object_list
    }
    return render(request, 'mainapp/category_products_list.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_product_create(request, category_pk):
    category = get_object_or_404(ProductCategory, pk=category_pk)
    if request.method == 'POST':
        form = AdminProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(
                'new_admin:category_products',
                kwargs={'pk': category.pk}
            ))
    else:
        form = AdminProductUpdateForm(
            initial={
                'category': category,
            }
        )

    context = {
        'page_title': 'продукты/создание',
        'form': form,
        'category': category,
    }
    return render(request, 'mainapp/product_update.html', context)


class ProductDetail(SuperUserOnlyMixin, PageTitleMixin, DetailView):
    model = Product
    page_title = 'админка/продукты'

gb/gshop/mainapp/views.py
import random

from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache
from django.db.models.signals import pre_save
from django.dispatch import receiver
from gshop import settings
from django.db import connection
from mainapp.models import Product, ProductCategory


def get_products():
    if settings.LOW_CACHE:
        key = 'all_products'
        products = cache.get(key)
        if products is None:
            products = Product.get_items()
            cache.set(key, products)
        return products
    return Product.get_items()


def get_products_by_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}_products'
        products = cache.get(key)
        if products is None:
            products = Product.get_items().filter(category_id=pk)
            cache.set(key, products)
        return products
    return Product.get_items().filter(category_id=pk)


def get_hot_product():
    product_ids = get_products().values_list('id', flat=True)
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)


def same_products(hot_product):
    return Product.get_items().filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:4]


def index(request):
    context = {'page_title': 'Главная', }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    contacts = [
        {'city': 'Москва',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
        {'city': 'Москва 1',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
        {'city': 'Москва 2',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
    ]
    context = {'page_title': 'Контакты',
               'contacts': contacts,
               }
    return render(request, 'mainapp/contact.html', context)


@never_cache
def products(request):
    hot_product = get_hot_product()
    context = {
        'page_title': 'Каталог',
        'hot_product': hot_product,
        'same_product': same_products(hot_product),
    }
    return render(request, 'mainapp/products.html', context)


# @cache_page(3600)
def category(request, pk):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все'}
        products = get_products()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = get_products_by_category(pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)
    context = {
        'page_title': 'Каталог',
        'category': category,
        'products': products, }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'страница продукта',
        'product': product,
    }
    return render(request, 'mainapp/product_page.html', context)


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=pk).first()
        return JsonResponse(
            {'price': product and product.price or 0}
        )


def db_profile_by_type(sender, q_type, queries):
    print(f'db profile {q_type} for {sender}:')
    for query in filter(lambda x: q_type in x,
                        map(lambda x: x['sql'],
                            queries)):
        print(query)


@receiver(pre_save, sender=ProductCategory)
def update_prod_cat_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)

gb/gshop/adminapp/templates/mainapp/category_products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
<div class="products_list">
    <a class="new_product btn btn-default"
       href={% url 'new_admin:category_product_create' category.pk %} >новый продукт</a>

    {% for object in object_list %}
    <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href={% url 'new_admin:product_view' pk=object.pk %}>подробнее</a>
            </button>
            <button>
                <a href={#% url 'myadmin:product_update' object.pk %#}>редактировать</a>
            </button>
            <button>
                <a href={#% url 'myadmin:product_delete' object.pk %#}>удалить</a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|capfirst }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

gb/gshop/adminapp/templates/mainapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <a href="{#% url 'myadmin:product_update' object.pk %#}"
                   class="btn btn-primary">
                    редактировать
                </a>
            </p>
            <p>
                <a href="{#% url 'myadmin:product_delete' object.pk %#}"
                   class="btn btn-danger">
                    удалить
                </a>
            </p>
            <p>
                <a href="{% url 'new_admin:category_products' object.category_id %}"
                   class="btn btn-default">
                    назад
                </a>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

gb/gshop/adminapp/templates/mainapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'new_admin:category_products' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

gb/gshop/adminapp/templates/mainapp/productcategory_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'new_admin:categories' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

gb/gshop/adminapp/templates/mainapp/productcategory_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'new_admin:categories' %}"
           class="btn btn-primary form-control last">
            к списку категорий
        </a>
    </div>
{% endblock %}

gb/gshop/adminapp/templates/mainapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'new_admin:category_create' %}"
           class="btn btn-primary new_user">
            новая категория
        </a>
        {% for category in object_list %}
            <div class="user_record {% if not category.is_active %}not_active{% endif %}">
                <div class="category_actions">
                    <a href="{% url 'new_admin:category_products' category.pk %}"
                       class="btn btn-info">
                        товары категории
                    </a>
                    <a href="{% url 'new_admin:category_update' category.pk %}"
                       class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{% url 'new_admin:category_delete' category.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ category.name }}</strong></p>
                </div>
                <div>
                    {{ category.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}