gb/gshop/authapp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

gb/gshop/gshop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

gb/gshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', mainapp.products, name='products'),

    path('category/<int:pk>/', mainapp.category, name='category'),
    path('product/<int:pk>/price/', mainapp.get_product_price),
    path('product/<int:pk>/', mainapp.product_page, name='product_page'),

]

gb/gshop/mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продуктов'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    price = models.DecimalField('цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name}({self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.select_related('category'). \
            filter(is_active=True, category__is_active=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']

gb/gshop/mainapp/views.py
import random

from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache
from django.db.models.signals import pre_save
from django.dispatch import receiver
from gshop import settings
from django.db import connection
from mainapp.models import Product, ProductCategory


def get_products():
    if settings.LOW_CACHE:
        key = 'all_products'
        products = cache.get(key)
        if products is None:
            products = Product.get_items()
            cache.set(key, products)
        return products
    return Product.get_items()


def get_products_by_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}_products'
        products = cache.get(key)
        if products is None:
            products = Product.get_items().filter(category_id=pk)
            cache.set(key, products)
        return products
    return Product.get_items().filter(category_id=pk)


def get_hot_product():
    product_ids = get_products().values_list('id', flat=True)
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)


def same_products(hot_product):
    return Product.get_items().filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:4]


def index(request):
    context = {'page_title': 'Главная', }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    contacts = [
        {'city': 'Москва',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
        {'city': 'Москва 1',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
        {'city': 'Москва 2',
         'phone': '+7-888-888-8888',
         'email': 'smth@google.com',
         'address': 'В пределах МКАД'},
    ]
    context = {'page_title': 'Контакты',
               'contacts': contacts,
               }
    return render(request, 'mainapp/contact.html', context)


@never_cache
def products(request):
    hot_product = get_hot_product()
    context = {
        'page_title': 'Каталог',
        'hot_product': hot_product,
        'same_product': same_products(hot_product),
    }
    return render(request, 'mainapp/products.html', context)


# @cache_page(3600)
def category(request, pk):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все'}
        products = get_products()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = get_products_by_category(pk)

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)
    context = {
        'page_title': 'Каталог',
        'category': category,
        'products': products, }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'страница продукта',
        'product': product,
    }
    return render(request, 'mainapp/product_page.html', context)


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=pk).first()
        return JsonResponse(
            {'price': product and product.price or 0}
        )


def db_profile_by_type(sender, q_type, queries):
    print(f'db profile {q_type} for {sender}:')
    for query in filter(lambda x: q_type in x,
                        map(lambda x: x['sql'],
                            queries)):
        print(query)


@receiver(pre_save, sender=ProductCategory)
def update_prod_cat_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)

gb/gshop/mainapp/templates/mainapp/includes/catalog_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'main:category' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}"> все</a></li>
        <li><a href="#">дом</a></li>
        <li><a href="#">офис</a></li>
        <li><a href="#">модерн</a></li>
        <li><a href="#">классика</a></li>
        {% for item in pcategory %}
        <li><a href="{% url 'main:category' item.pk %}"
               class="{% if request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">{{ item.name }}</a></li>
        {% endfor %}

    </ul>
</div>

gb/gshop/mainapp/templates/mainapp/includes/main_menu.html
{% load static %}
<div class="header clearfix">
    <a href="{% url 'main:index' %}" class="logo"></a>
    <ul class="menu">
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    {{ user.first_name|default:"пользователь"|title }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'orders:index' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'new_admin:index' %}">
                Админка
            </a>
        </li>
        {% endif %}
        <li>
            <a href="{% url 'main:index' %}"
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}"
               class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' %}active{% endif %}">
                продукты
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                контакты
            </a>
        </li>

        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">
                выйти
            </a>
            {% else %}
            <a href="{% url 'auth:login' %}">
                войти
            </a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        {% if user.is_authenticated %}
        <span>{{ user.basket_price|floatformat:0 }} &#8381; ({{ user.basket_quantity }} ед.)</span>
        {% endif %}
    </a>
</div>